<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>com.esri</groupId>
    <artifactId>geofunctions</artifactId>
    <version>0.27</version>
    <packaging>jar</packaging>

    <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <java.version>11</java.version>
        <scala.compact>2.12</scala.compact>
        <scala.version>${scala.compact}.18</scala.version>
        <spark.compact>3.5</spark.compact>
        <spark.version>${spark.compact}.6</spark.version>
        <spark.scope>provided</spark.scope>
    </properties>

    <repositories>
        <!--
        <repository>
            <id>osgeo</id>
            <url>https://repo.osgeo.org/repository/release</url>
            <snapshots>
                <enabled>false</enabled>
                <updatePolicy>always</updatePolicy>
            </snapshots>
            <releases>
                <enabled>true</enabled>
                <updatePolicy>daily</updatePolicy>
            </releases>
        </repository>
        -->
    </repositories>

    <dependencies>
        <dependency>
            <groupId>org.apache.spark</groupId>
            <artifactId>spark-core_${scala.compact}</artifactId>
            <version>${spark.version}</version>
            <scope>${spark.scope}</scope>
        </dependency>
        <dependency>
            <groupId>org.apache.spark</groupId>
            <artifactId>spark-sql_${scala.compact}</artifactId>
            <version>${spark.version}</version>
            <scope>${spark.scope}</scope>
        </dependency>
        <dependency>
            <groupId>com.github.plokhotnyuk.rtree2d</groupId>
            <artifactId>rtree2d-core_${scala.compact}</artifactId>
            <version>0.11.15-SNAPSHOT</version>
        </dependency>
        <dependency>
            <groupId>com.esri</groupId>
            <artifactId>webmercator</artifactId>
            <version>1.13-${scala.compact}</version>
        </dependency>
        <dependency>
            <groupId>com.esri</groupId>
            <artifactId>grid-hex</artifactId>
            <version>2.12-${scala.compact}</version>
            <exclusions>
                <exclusion>
                    <groupId>org.scala-lang</groupId>
                    <artifactId>*</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>com.beust</groupId>
                    <artifactId>*</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <groupId>com.esri</groupId>
            <artifactId>spark-shp</artifactId>
            <version>0.31-${spark.compact}-${scala.compact}</version>
            <exclusions>
                <exclusion>
                    <groupId>com.fasterxml.jackson.core</groupId>
                    <artifactId>*</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <groupId>com.esri</groupId>
            <artifactId>filegdb</artifactId>
            <version>0.65-${spark.compact}-${scala.compact}</version>
        </dependency>
        <dependency>
            <groupId>com.esri.geometry</groupId>
            <artifactId>esri-geometry-api</artifactId>
            <version>2.2.5-SNAPSHOT</version>
            <scope>compile</scope>
            <exclusions>
                <exclusion>
                    <groupId>com.fasterxml.jackson.core</groupId>
                    <artifactId>*</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>org.codehaus.jackson</groupId>
                    <artifactId>*</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>com.google.protobuf</groupId>
                    <artifactId>*</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <groupId>com.uber</groupId>
            <artifactId>h3</artifactId>
            <version>4.1.1</version>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>org.scalatest</groupId>
            <artifactId>scalatest_${scala.compact}</artifactId>
            <!--version>3.0.5</version-->
            <version>3.2.9</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.scalacheck</groupId>
            <artifactId>scalacheck_${scala.compact}</artifactId>
            <version>1.14.3</version>
            <scope>test</scope>
        </dependency>
        <!--
        <dependency>
            <groupId>org.graalvm.polyglot</groupId>
            <artifactId>polyglot</artifactId>
            <version>24.1.1</version>
        </dependency>
        <dependency>
            <groupId>org.graalvm.polyglot</groupId>
            <artifactId>python</artifactId>
            <version>24.1.1</version>
            <type>pom</type>
        </dependency>
        -->
    </dependencies>

    <build>
        <!--
        <finalName>${project.artifactId}-${spark.compact}-${project.version}</finalName>
        -->
        <plugins>
            <!--plugin>
                <groupId>org.graalvm.python</groupId>
                <artifactId>graalpy-maven-plugin</artifactId>
                <version>24.1.1</version>
                <executions>
                    <execution>
                        <configuration>
                            <packages>
                                <package>litellm==1.55.8</package>
                            </packages>
                        </configuration>
                        <goals>
                            <goal>process-graalpy-resources</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin-->
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.14.1</version>
                <configuration>
                    <source>${java.version}</source>
                    <target>${java.version}</target>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-surefire-plugin</artifactId>
                <version>3.5.0</version>
                <configuration>
                    <skipTests>true</skipTests>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-jar-plugin</artifactId>
                <version>3.4.2</version>
                <executions>
                    <execution>
                        <goals>
                            <goal>jar</goal>
                        </goals>
                        <configuration>
                            <classifier>${scala.compact}</classifier>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <groupId>net.alchim31.maven</groupId>
                <artifactId>scala-maven-plugin</artifactId>
                <version>4.9.6</version>
                <executions>
                    <execution>
                        <id>scala-compile-first</id>
                        <phase>process-resources</phase>
                        <goals>
                            <goal>add-source</goal>
                            <goal>compile</goal>
                        </goals>
                    </execution>
                    <execution>
                        <id>scala-test-compile-first</id>
                        <phase>process-test-resources</phase>
                        <goals>
                            <goal>testCompile</goal>
                        </goals>
                    </execution>
                </executions>
                <configuration>
                    <scalaCompatVersion>${scala.compact}</scalaCompatVersion>
                    <scalaVersion>${scala.version}</scalaVersion>
                    <recompileMode>incremental</recompileMode>
                    <args>
                        <arg>-Yresolve-term-conflict:package</arg>
                        <arg>-opt:l:inline</arg>
                        <arg>-opt-inline-from:com.esri.**</arg>
                        <arg>-opt-warnings</arg>
                    </args>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-clean-plugin</artifactId>
                <version>3.5.0</version>
                <configuration>
                    <filesets>
                        <fileset>
                            <directory>build</directory>
                            <followSymlinks>false</followSymlinks>
                        </fileset>
                        <fileset>
                            <directory>dist</directory>
                            <followSymlinks>false</followSymlinks>
                        </fileset>
                    </filesets>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-shade-plugin</artifactId>
                <version>3.6.1</version>
                <executions>
                    <execution>
                        <phase>package</phase>
                        <goals>
                            <goal>shade</goal>
                        </goals>
                        <configuration>
                            <artifactSet>
                                <excludes>
                                    <exclude>it.geosolutions.jgridshift:*</exclude>
                                    <exclude>jakarta.annotation:*</exclude>
                                    <exclude>javax.inject:*</exclude>
                                    <exclude>javax.measure:*</exclude>
                                    <exclude>log4j:*</exclude>
                                    <exclude>org.eclipse.emf:*</exclude>
                                    <exclude>org.ejml:*</exclude>
                                    <exclude>org.scala-lang:*</exclude>
                                    <exclude>org.slf4j:*</exclude>
                                    <exclude>si.uom:*</exclude>
                                    <exclude>systems.uom:*</exclude>
                                    <exclude>tech.units:*</exclude>
                                    <exclude>tech.uom.lib:*</exclude>
                                    <exclude>com.esri.arcgis.protobuf:arcgis-pbf:*</exclude>
                                    <exclude>commons-io:commons-io:*</exclude>
                                    <exclude>javax.xml.bind:jaxb-api:*</exclude>
                                    <exclude>org.ehcache:ehcache:*</exclude>
                                    <exclude>org.glassfish.jaxb:jaxb-runtime</exclude>
                                    <exclude>org.glassfish.jaxb:txw2</exclude>
                                    <!-- <exclude>org.aspectj:*</exclude> -->
                                </excludes>
                            </artifactSet>
                            <transformers>
                                <transformer
                                        implementation="org.apache.maven.plugins.shade.resource.ServicesResourceTransformer"/>
                                <transformer
                                        implementation="org.apache.maven.plugins.shade.resource.AppendingTransformer">
                                    <resource>reference.conf</resource>
                                </transformer>
                            </transformers>
                            <filters>
                                <filter>
                                    <artifact>*:*</artifact>
                                    <excludes>
                                        <exclude>META-INF/*.SF</exclude>
                                        <exclude>META-INF/*.DSA</exclude>
                                        <exclude>META-INF/*.RSA</exclude>
                                        <exclude>META-INF/license/**</exclude>
                                        <exclude>META-INF/*</exclude>
                                        <exclude>META-INF/maven/**</exclude>
                                        <exclude>LICENSE</exclude>
                                        <exclude>NOTICE</exclude>
                                        <exclude>/*.txt</exclude>
                                        <exclude>build.properties</exclude>
                                    </excludes>
                                </filter>
                            </filters>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <groupId>org.codehaus.mojo</groupId>
                <artifactId>exec-maven-plugin</artifactId>
                <version>3.6.2</version>
                <executions>
                    <execution>
                        <phase>validate</phase>
                        <goals>
                            <goal>exec</goal>
                        </goals>
                        <configuration>
                            <executable>python3</executable>
                            <arguments>
                                <argument>pom_to_pyproject.py</argument>
                            </arguments>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>

    <profiles>
        <profile>
            <id>spark-3.3</id>
            <activation>
                <activeByDefault>false</activeByDefault>
            </activation>
            <properties>
                <scala.compact>2.12</scala.compact>
                <scala.version>${scala.compact}.15</scala.version>
                <spark.compact>3.3</spark.compact>
                <spark.version>${spark.compact}.2</spark.version>
            </properties>
        </profile>
        <profile>
            <id>spark-3.4</id>
            <activation>
                <activeByDefault>false</activeByDefault>
            </activation>
            <properties>
                <scala.compact>2.12</scala.compact>
                <scala.version>${scala.compact}.17</scala.version>
                <spark.compact>3.4</spark.compact>
                <spark.version>${spark.compact}.1</spark.version>
            </properties>
        </profile>
        <profile>
            <id>spark-3.5</id>
            <activation>
                <activeByDefault>true</activeByDefault>
            </activation>
            <properties>
                <scala.compact>2.12</scala.compact>
                <scala.version>${scala.compact}.18</scala.version>
                <spark.compact>3.5</spark.compact>
                <spark.version>${spark.compact}.7</spark.version>
            </properties>
        </profile>
        <profile>
            <id>spark-4.0</id>
            <activation>
                <activeByDefault>false</activeByDefault>
            </activation>
            <properties>
                <java.version>17</java.version>
                <scala.compact>2.13</scala.compact>
                <scala.version>${scala.compact}.16</scala.version>
                <spark.compact>4.0</spark.compact>
                <spark.version>${spark.compact}.0</spark.version>
            </properties>
        </profile>
        <profile>
            <id>spark-scope-provided</id>
            <activation>
                <activeByDefault>true</activeByDefault>
            </activation>
            <properties>
                <spark.scope>provided</spark.scope>
            </properties>
        </profile>
        <profile>
            <id>spark-scope-compile</id>
            <activation>
                <activeByDefault>false</activeByDefault>
            </activation>
            <properties>
                <spark.scope>compile</spark.scope>
            </properties>
        </profile>
    </profiles>
</project>
