[project]
name = "geofunctions"
version = "0.28"
requires-python = ">3.10"
readme = "README.md"
dependencies = [ "pyspark==3.5.9; sys_platform != 'win32'", "pyspark==3.5.4; sys_platform == 'win32'", "toml",]
[[project.authors]]
name = "mraad"
email = "mraad@esri.com"

[build-system]
requires = [ "setuptools", "wheel",]
build-backend = "setuptools.build_meta"

[project.license]
text = "Apache-2.0"

[project.optional-dependencies]
jupyter = [ "black", "contextily", "duckdb", "fastparquet", "folium", "gdal", "geopandas", "ipywidgets", "isort", "jupyterlab>=4.3.4", "jupyterlab_code_formatter", "mapclassify", "matplotlib", "pandas", "pyarrow", "seaborn",]

[tool.setuptools.packages.find]
where = [ "src/main/python",]
