[project]
name = "geofunctions"
version = "0.24"
requires-python = ">3.10"
readme = "README.md"
dependencies = [ "black", "contextily", "duckdb", "fastparquet", "folium", "gdal==3.11.0", "geopandas", "ipywidgets", "isort", "jupyterlab>=4.3.4", "jupyterlab_code_formatter", "mapclassify", "matplotlib", "pandas", "pyarrow", "pyspark==3.5.6", "seaborn",]
[[project.authors]]
name = "mraad"
email = "mraad@esri.com"

[build-system]
requires = [ "setuptools", "wheel",]
build-backend = "setuptools.build_meta"

[project.license]
text = "Apache-2.0"

[tool.setuptools.packages.find]
where = [ "src/main/python",]
